"""Initial migration

Revision ID: 734177879b21
Revises: 
Create Date: 2026-09-02 14:44:27.994913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '734177879b21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aoi_geom', 'aois', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_aois_id'), 'aois', ['id'], unique=False)
    op.create_index(op.f('ix_aois_name'), 'aois', ['name'], unique=False)
    op.create_table('detection_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_geom', 'detection_clusters', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_detection_clusters_id'), 'detection_clusters', ['id'], unique=False)
    op.create_table('satellite_scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('acquisition_time', sa.DateTime(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scene_geom', 'satellite_scenes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_satellite_scenes_id'), 'satellite_scenes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('satellite_tiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('minio_path', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['satellite_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_satellite_tile_embedding', 'satellite_tiles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_tile_geom', 'satellite_tiles', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_satellite_tiles_id'), 'satellite_tiles', ['id'], unique=False)
    op.create_table('temporal_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('before_scene_id', sa.String(), nullable=True),
    sa.Column('after_scene_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['after_scene_id'], ['satellite_scenes.id'], ),
    sa.ForeignKeyConstraint(['before_scene_id'], ['satellite_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporal_pairs_id'), 'temporal_pairs', ['id'], unique=False)
    op.create_table('change_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['detection_clusters.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['temporal_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detection_geom', 'change_detections', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_change_detections_id'), 'change_detections', ['id'], unique=False)
    op.create_table('analyst_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['change_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_reviews_id'), 'analyst_reviews', ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_analyst_reviews_id'), table_name='analyst_reviews')
    op.drop_table('analyst_reviews')
    op.drop_index(op.f('ix_change_detections_id'), table_name='change_detections')
    op.drop_index('idx_detection_geom', table_name='change_detections', postgresql_using='gist')
    op.drop_index('idx_change_detections_geom', table_name='change_detections', postgresql_using='gist')
    op.drop_table('change_detections')
    op.drop_index(op.f('ix_temporal_pairs_id'), table_name='temporal_pairs')
    op.drop_table('temporal_pairs')
    op.drop_index(op.f('ix_satellite_tiles_id'), table_name='satellite_tiles')
    op.drop_index('idx_tile_geom', table_name='satellite_tiles', postgresql_using='gist')
    op.drop_index('idx_satellite_tiles_geom', table_name='satellite_tiles', postgresql_using='gist')
    op.drop_index('idx_satellite_tile_embedding', table_name='satellite_tiles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('satellite_tiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_satellite_scenes_id'), table_name='satellite_scenes')
    op.drop_index('idx_scene_geom', table_name='satellite_scenes', postgresql_using='gist')
    op.drop_index('idx_satellite_scenes_geom', table_name='satellite_scenes', postgresql_using='gist')
    op.drop_table('satellite_scenes')
    op.drop_index(op.f('ix_detection_clusters_id'), table_name='detection_clusters')
    op.drop_index('idx_detection_clusters_geom', table_name='detection_clusters', postgresql_using='gist')
    op.drop_index('idx_cluster_geom', table_name='detection_clusters', postgresql_using='gist')
    op.drop_table('detection_clusters')
    op.drop_index(op.f('ix_aois_name'), table_name='aois')
    op.drop_index(op.f('ix_aois_id'), table_name='aois')
    op.drop_index('idx_aois_geom', table_name='aois', postgresql_using='gist')
    op.drop_index('idx_aoi_geom', table_name='aois', postgresql_using='gist')
    op.drop_table('aois')
    # ### end Alembic commands ###
